version: '3'

services:
    flask_app:
        container_name: flask_app
        restart: always
        build: ./flask_app
        ports:
            - "7000:7000"
        command: gunicorn -w 1 -b :7000 app:app

    nginx:
        container_name: nginx
        restart: always
        build: ./nginx
        ports:
            - "80:80"
        depends_on:
            - flask_app